### ISSUE TITLE
GCP Deployment broken due to update in Kubernetes provider

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub-cloud#263]
## Describe the bug
GCP deployment is broken due to the update in Kubernetes provider. It seems there are more changes.

## How can we help?
Help us help you.
* What are you trying to achieve?
Deploy QHub on GCP

* How can we reproduce the problem?
Deploy QHub on GCP via latest master

* What is the expected behaviour?
Deploy successfully

* And what is currently happening?
Deployment fails

* Any error messages?

```

Error: Unsupported block type

  on .terraform/modules/kubernetes/modules/gcp/kubernetes/nvidia_installer.tf line 77, in resource "kubernetes_daemonset" "nvidia_installer":
  77:             requests ***

Blocks of type "requests" are not expected here. Did you mean to define
argument "requests"? If so, use the equals sign to assign it a value.

Error: Terraform exited with code 1.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/bin/qhub", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/qhub/__main__.py", line 7, in main
    cli(sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/qhub/cli/__init__.py", line 40, in cli
    args.func(args)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/qhub/cli/deploy.py", line 44, in handle_deploy
    deploy_configuration(
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/qhub/deploy.py", line 21, in deploy_configuration
    guided_install(config, dns_provider, dns_auto_provision, disable_prompt)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/qhub/deploy.py", line 65, in guided_install
    raise ValueError(f"IP Address not found in: ***cmd_output***")
r: IP Address not found in: b'[command]/home/runner/work/_temp/5e923156-ffe1-41f9-afc5-95e78a099e60/terraform-bin output --json\n***\n::debug::Terraform exited with code 0.\n::debug::stdout: ***%0A\n::debug::stderr: \n::debug::exitcode: 0\n::set-output name=stdout::***%0A\n::set-output name=stderr::\n::set-output name=exitcode::0\n'
```

## Your environment
Describe the environment in which you are experiencing the bug.
> Include your conda version (use `conda --version`), k8s and any other relevant details.

**Comment by aktech** [comment]
The problem is due to this update:
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide#changes-to-the-limits-and-requests-attributes-on-all-resources-that-support-a-podspec

>The limits and requests attributes on all resources that include a PodSpec, are now a map. This means that limits {} must be changed to limits = {}, and the same for requests. This change impacts the following resources: kubernetes_deployment, kubernetes_daemonset, kubernetes_stateful_set, kubernetes_pod, kubernetes_job, kubernetes_cron_job.
